global:
  scrape_interval: 15s  # Intervalo de tiempo para recopilar métricas

scrape_configs:
  - job_name: 'my-nest-app'  # Nombre de tu aplicación
    metrics_path: '/metrics'   # Ruta de las métricas (debe coincidir con lo que expone tu aplicación)
    static_configs:
      - targets: ['localhost:3000']  # Cambia esto por la dirección y el puerto donde se ejecuta tu aplicación
